#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 10 17:44:22 2026

@author: Willie
"""



"""
======================================================================
SecureGAT-Agent: Injection-aware AST Graph Annotation V2
======================================================================

Purpose
-------
Map SolidiFI BugLog injection locations to the CLEAN AST graphs
generated by Step 05.

IMPORTANT
---------
This version is designed for the CLEAN AST representation.

It does NOT perform naive interval-overlap labeling of every ancestor.

Instead:

    BugLog line range
          |
          v
    source byte interval
          |
          v
    AST nodes contained in injection region
          |
          v
    remove unnecessary ancestor nodes
          |
          v
    injection-aware node labels

Input
-----
    datasets/graph_dataset/<vulnerability>/buggy_N.pt

    datasets/SolidiFI-benchmark/buggy_contracts/
        <vulnerability>/buggy_N.sol
        <vulnerability>/BugLog_N.csv

Output
------
    datasets/annotated_graph_dataset/<vulnerability>/buggy_N.pt

Reports
-------
    datasets/annotated_graph_dataset/annotation_report.json
    datasets/annotated_graph_dataset/injection_audit.csv
    datasets/annotated_graph_dataset/annotation_examples.txt

======================================================================
"""

import os
import csv
import json
import shutil

import torch


# ======================================================================
# Configuration
# ======================================================================

GRAPH_ROOT = "datasets/graph_dataset"

BUG_ROOT = os.path.join(
    "datasets",
    "SolidiFI-benchmark",
    "buggy_contracts"
)

OUTPUT_ROOT = "datasets/annotated_graph_dataset"

VULNERABILITIES = [
    "Overflow-Underflow",
    "Re-entrancy",
    "TOD",
    "Timestamp-Dependency",
    "Unchecked-Send",
    "Unhandled-Exceptions",
    "tx.origin"
]

# ----------------------------------------------------------------------
# Annotation strategy
# ----------------------------------------------------------------------
#
# "contained" is the primary strategy:
#
# A node is considered part of the injected region when its complete
# source span lies inside the BugLog source interval.
#
# This prevents a large ancestor such as ContractDefinition from being
# marked positive merely because it contains the injection.
#
# ----------------------------------------------------------------------

ANNOTATION_STRATEGY = "contained"

# Maximum number of examples written to the human-readable report.
MAX_EXAMPLES_PER_VULNERABILITY = 10


# ======================================================================
# Bug type normalization
# ======================================================================

def normalize_bug_type(name):
    """
    Normalize SolidiFI BugLog vulnerability names.
    """

    if name is None:
        return ""

    name = str(name).strip()

    mapping = {
        "Re+AC0-erntrancy": "Re-entrancy",
        "Re-entrancy": "Re-entrancy",

        "Overflow-Underflow":
            "Overflow-Underflow",

        "Unchecked-Send":
            "Unchecked-Send",

        "Unhandled-Exceptions":
            "Unhandled-Exceptions",

        "Timestamp-Dependency":
            "Timestamp-Dependency",

        "TOD":
            "TOD",

        "tx.origin":
            "tx.origin",
    }

    return mapping.get(name, name)


# ======================================================================
# Contract ID
# ======================================================================

def contract_number_from_graph(filename):
    """
    buggy_1.pt -> 1
    buggy_25.pt -> 25
    """

    base = os.path.basename(filename)

    if not base.startswith("buggy_"):
        return None

    try:
        value = base[len("buggy_"):]
        value = value.split(".")[0]
        return int(value)
    except Exception:
        return None


# ======================================================================
# Load Solidity source
# ======================================================================

def load_source(vulnerability, contract_id):
    """
    Load the exact Solidity source corresponding to the graph.
    """

    path = os.path.join(
        BUG_ROOT,
        vulnerability,
        f"buggy_{contract_id}.sol"
    )

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Source file not found: {path}"
        )

    with open(path, "rb") as f:
        return f.read()


# ======================================================================
# Source line offsets
# ======================================================================

def build_line_offsets(source_bytes):
    """
    Build zero-based source-byte offsets.

    line_offsets[0] = byte offset of line 1
    line_offsets[1] = byte offset of line 2
    ...

    Solidity AST src offsets are byte-based for the AST used here.
    """

    offsets = [0]

    for i, byte in enumerate(source_bytes):

        if byte == 10:  # LF / newline
            offsets.append(i + 1)

    return offsets


# ======================================================================
# BugLog line range -> source byte interval
# ======================================================================

def injection_to_source_interval(
    loc,
    length,
    line_offsets,
    source_length
):
    """
    Convert:

        loc    = starting source line
        length = number of source lines

    into:

        [start_byte, end_byte)

    Example:

        loc=22
        length=8

    corresponds to lines:

        22 ... 29

    """

    try:
        loc = int(loc)
        length = int(length)
    except Exception:
        return None

    if loc < 1:
        return None

    if length < 1:
        return None

    start_line_index = loc - 1

    if start_line_index >= len(line_offsets):
        return None

    start_offset = line_offsets[
        start_line_index
    ]

    # End of the last included line.
    end_line_index = (
        start_line_index + length
    )

    if end_line_index < len(line_offsets):

        end_offset = line_offsets[
            end_line_index
        ]

    else:

        end_offset = source_length

    if end_offset <= start_offset:
        return None

    return (
        start_offset,
        end_offset
    )


# ======================================================================
# Load BugLog
# ======================================================================

def load_buglog(
    vulnerability,
    contract_id
):
    """
    Load exactly ONE BugLog.

    buggy_1.pt
        -> BugLog_1.csv

    buggy_2.pt
        -> BugLog_2.csv

    etc.
    """

    path = os.path.join(
        BUG_ROOT,
        vulnerability,
        f"BugLog_{contract_id}.csv"
    )

    injections = []

    if not os.path.exists(path):

        print(
            f"WARNING: BugLog not found: {path}"
        )

        return injections

    with open(
        path,
        "r",
        encoding="utf-8",
        newline=""
    ) as f:

        reader = csv.DictReader(f)

        for row_number, row in enumerate(
            reader,
            start=2
        ):

            try:

                loc = int(
                    str(row.get("loc", "")).strip()
                )

                length = int(
                    str(row.get("length", "")).strip()
                )

            except Exception:

                print(
                    f"WARNING: invalid BugLog row "
                    f"{path}:{row_number}"
                )

                continue

            bug_type = normalize_bug_type(
                row.get(
                    "bug type",
                    ""
                )
            )

            injections.append({

                "loc": loc,

                "length": length,

                "bug_type": bug_type,

                "approach":
                    row.get(
                        "approach",
                        ""
                    ),

                "buglog_row":
                    row_number
            })

    return injections


# ======================================================================
# Graph node interval
# ======================================================================

def get_node_interval(
    graph,
    node_index
):
    """
    Return:

        (start, end)

    or None.

    Clean Step 05 graphs contain:

        node_start
        node_end
    """

    if not hasattr(graph, "node_start"):
        return None

    if not hasattr(graph, "node_end"):
        return None

    try:

        start = int(
            graph.node_start[node_index].item()
        )

        end = int(
            graph.node_end[node_index].item()
        )

    except Exception:

        return None

    # -1 means no source mapping.
    if start < 0 or end < 0:
        return None

    if end <= start:
        return None

    return (
        start,
        end
    )


# ======================================================================
# Node type name
# ======================================================================

def get_node_type_name(
    graph,
    node_index
):
    """
    Retrieve the human-readable AST node type.
    """

    if hasattr(
        graph,
        "node_type_name"
    ):

        try:
            return str(
                graph.node_type_name[
                    node_index
                ]
            )
        except Exception:
            pass

    return "Unknown"


# ======================================================================
# Interval containment
# ======================================================================

def interval_contained(
    node_start,
    node_end,
    injection_start,
    injection_end
):
    """
    True when the complete AST node span is inside
    the BugLog injection span.
    """

    return (
        node_start >= injection_start
        and
        node_end <= injection_end
    )


# ======================================================================
# Interval overlap
# ======================================================================

def interval_overlap(
    node_start,
    node_end,
    injection_start,
    injection_end
):
    """
    Half-open interval overlap.
    """

    return (
        node_start < injection_end
        and
        node_end > injection_start
    )


# ======================================================================
# Node containment
# ======================================================================

def node_contains(
    outer_start,
    outer_end,
    inner_start,
    inner_end
):
    """
    Determine whether one AST node contains another.
    """

    return (
        outer_start <= inner_start
        and
        outer_end >= inner_end
        and
        (
            outer_start < inner_start
            or
            outer_end > inner_end
        )
    )


# ======================================================================
# Remove unnecessary ancestor nodes
# ======================================================================

def remove_redundant_ancestors(
    graph,
    candidate_indices
):
    """
    Given AST nodes inside an injection region, remove nodes that
    merely contain another selected node.

    This prevents:

        FunctionDefinition
            Block
                ExpressionStatement
                    FunctionCall

    from all being labeled simply because they are nested.

    The more specific AST nodes remain.

    Important:
    This operates ONLY on candidate nodes already inside the
    injection interval.
    """

    if not candidate_indices:
        return []

    intervals = {}

    for index in candidate_indices:

        interval = get_node_interval(
            graph,
            index
        )

        if interval is not None:

            intervals[index] = interval

    if not intervals:
        return []

    keep = []

    for index, (
        start,
        end
    ) in intervals.items():

        contains_other = False

        for other, (
            other_start,
            other_end
        ) in intervals.items():

            if other == index:
                continue

            if node_contains(
                start,
                end,
                other_start,
                other_end
            ):

                contains_other = True
                break

        if not contains_other:
            keep.append(index)

    return sorted(
        keep
    )


# ======================================================================
# Find nodes inside injection
# ======================================================================

def find_injection_nodes(
    graph,
    injection_start,
    injection_end
):
    """
    Main AST localization algorithm.

    Stage 1:
        Find AST nodes fully contained in the BugLog region.

    Stage 2:
        Remove redundant ancestors.

    Stage 3:
        If no contained node exists, use the smallest overlapping
        source-mapped AST nodes as a fallback.

    Returns:

        selected_nodes
        all_contained_nodes
        fallback_nodes
    """

    num_nodes = int(
        graph.num_nodes
    )

    contained = []

    overlapping = []

    for node_index in range(
        num_nodes
    ):

        interval = get_node_interval(
            graph,
            node_index
        )

        if interval is None:
            continue

        node_start, node_end = interval

        if interval_contained(
            node_start,
            node_end,
            injection_start,
            injection_end
        ):

            contained.append(
                node_index
            )

        elif interval_overlap(
            node_start,
            node_end,
            injection_start,
            injection_end
        ):

            overlapping.append(
                node_index
            )

    # --------------------------------------------------------------
    # Primary selection
    # --------------------------------------------------------------

    selected = remove_redundant_ancestors(
        graph,
        contained
    )

    # --------------------------------------------------------------
    # Fallback
    # --------------------------------------------------------------
    #
    # Sometimes an injection boundary cuts through an AST node.
    # In that situation there may be no completely contained node.
    #
    # Select the smallest overlapping AST nodes.
    #

    fallback = []

    if not selected:

        if overlapping:

            # Find minimum source span among overlaps.
            spans = []

            for index in overlapping:

                interval = get_node_interval(
                    graph,
                    index
                )

                if interval is None:
                    continue

                start, end = interval

                span = end - start

                spans.append(
                    (
                        span,
                        index
                    )
                )

            if spans:

                min_span = min(
                    span
                    for span, _
                    in spans
                )

                fallback = sorted(
                    index
                    for span, index
                    in spans
                    if span == min_span
                )

                selected = fallback

    return (
        selected,
        contained,
        fallback
    )


# ======================================================================
# Annotate ONE graph
# ======================================================================

def annotate_graph(
    graph,
    injections,
    source_bytes
):
    """
    Annotate one graph.

    New graph attributes:

        injection_label
        injection_id
        injection_count
        matched_injection_count
        unmatched_injection_count

    Additional metadata:

        injection_node_type
        injection_node_depth
    """

    num_nodes = int(
        graph.num_nodes
    )

    # --------------------------------------------------------------
    # Binary node label
    # --------------------------------------------------------------

    injection_label = torch.zeros(
        num_nodes,
        dtype=torch.long
    )

    # --------------------------------------------------------------
    # Injection ID
    # --------------------------------------------------------------

    injection_id = torch.full(
        (
            num_nodes,
        ),
        -1,
        dtype=torch.long
    )

    # --------------------------------------------------------------
    # Number of injections assigned to each node
    # --------------------------------------------------------------

    injection_count = torch.zeros(
        num_nodes,
        dtype=torch.long
    )

    # --------------------------------------------------------------
    # Build source line offsets
    # --------------------------------------------------------------

    line_offsets = build_line_offsets(
        source_bytes
    )

    source_length = len(
        source_bytes
    )

    matched_injections = 0
    unmatched_injections = 0

    injection_records = []

    # ==================================================================
    # Process each BugLog injection
    # ==================================================================

    for injection_index, injection in enumerate(
        injections
    ):

        loc = injection["loc"]
        length = injection["length"]

        interval = injection_to_source_interval(
            loc,
            length,
            line_offsets,
            source_length
        )

        # --------------------------------------------------------------
        # Invalid source interval
        # --------------------------------------------------------------

        if interval is None:

            unmatched_injections += 1

            injection_records.append({

                "injection_id":
                    injection_index,

                "buglog_row":
                    injection.get(
                        "buglog_row"
                    ),

                "loc":
                    loc,

                "length":
                    length,

                "bug_type":
                    injection.get(
                        "bug_type",
                        ""
                    ),

                "source_start":
                    None,

                "source_end":
                    None,

                "matched":
                    False,

                "selection_method":
                    "invalid_interval",

                "matched_nodes":
                    []
            })

            continue

        injection_start, injection_end = interval

        # --------------------------------------------------------------
        # Find AST nodes
        # --------------------------------------------------------------

        (
            selected_nodes,
            contained_nodes,
            fallback_nodes
        ) = find_injection_nodes(
            graph,
            injection_start,
            injection_end
        )

        # --------------------------------------------------------------
        # Match result
        # --------------------------------------------------------------

        if selected_nodes:

            matched_injections += 1

            if fallback_nodes:

                selection_method = (
                    "smallest_overlapping"
                )

            else:

                selection_method = (
                    "contained_innermost"
                )

            # ----------------------------------------------------------
            # Label selected nodes
            # ----------------------------------------------------------

            for node_index in selected_nodes:

                injection_label[
                    node_index
                ] = 1

                injection_count[
                    node_index
                ] += 1

                # Preserve first injection ID.
                if injection_id[
                    node_index
                ] == -1:

                    injection_id[
                        node_index
                    ] = injection_index

        else:

            matched_injections += 0
            unmatched_injections += 1

            selection_method = (
                "no_source_mapped_node"
            )

        # --------------------------------------------------------------
        # Node type information
        # --------------------------------------------------------------

        node_types = {}

        for node_index in selected_nodes:

            node_type = get_node_type_name(
                graph,
                node_index
            )

            node_types[node_type] = (
                node_types.get(
                    node_type,
                    0
                ) + 1
            )

        # --------------------------------------------------------------
        # Record
        # --------------------------------------------------------------

        injection_records.append({

            "injection_id":
                injection_index,

            "buglog_row":
                injection.get(
                    "buglog_row"
                ),

            "loc":
                loc,

            "length":
                length,

            "bug_type":
                injection.get(
                    "bug_type",
                    ""
                ),

            "approach":
                injection.get(
                    "approach",
                    ""
                ),

            "source_start":
                injection_start,

            "source_end":
                injection_end,

            "source_length":
                injection_end -
                injection_start,

            "matched":
                bool(selected_nodes),

            "selection_method":
                selection_method,

            "contained_node_count":
                len(contained_nodes),

            "matched_node_count":
                len(selected_nodes),

            "matched_nodes":
                selected_nodes,

            "node_types":
                node_types
        })

    # ==================================================================
    # Attach annotations
    # ==================================================================

    graph.injection_label = (
        injection_label
    )

    graph.injection_id = (
        injection_id
    )

    graph.injection_count = (
        injection_count
    )

    graph.num_injections = (
        len(injections)
    )

    graph.num_matched_injections = (
        matched_injections
    )

    graph.num_unmatched_injections = (
        unmatched_injections
    )

    graph.annotation_version = (
        "step06_v2_clean_ast"
    )

    graph.annotation_strategy = (
        ANNOTATION_STRATEGY
    )

    return (
        matched_injections,
        unmatched_injections,
        injection_records
    )


# ======================================================================
# Write CSV audit
# ======================================================================

def write_injection_audit(
    path,
    records
):
    """
    Write one row per BugLog injection.
    """

    fieldnames = [
        
        "vulnerability",
    
        "contract_id",
    
        "graph",
    
        "injection_id",
    
        "buglog_row",
    
        "loc",
    
        "length",
    
        "bug_type",
    
        "approach",
    
        "source_start",
    
        "source_end",
    
        "source_length",
    
        "matched",
    
        "selection_method",
    
        "contained_node_count",
    
        "matched_node_count",
    
        "matched_nodes",
    
        "node_types"        

       
    ]
    

    with open(
        path,
        "w",
        encoding="utf-8",
        newline=""
    ) as f:

        writer = csv.DictWriter(
            f,
            fieldnames=fieldnames
        )

        writer.writeheader()

        for record in records:

            row = dict(record)

            row["matched_nodes"] = json.dumps(
                record.get(
                    "matched_nodes",
                    []
                )
            )

            row["node_types"] = json.dumps(
                record.get(
                    "node_types",
                    {}
                ),
                sort_keys=True
            )

            writer.writerow(row)


# ======================================================================
# Main
# ======================================================================

def main():

    print()
    print("=" * 70)
    print(
        "SecureGAT-Agent Injection-aware AST Graph Annotation V2"
    )
    print("=" * 70)
    print()

    print(
        "Execution device: CPU"
    )

    print(
        "AST annotation strategy:",
        ANNOTATION_STRATEGY
    )

    print()

    # --------------------------------------------------------------
    # Create output
    # --------------------------------------------------------------

    os.makedirs(
        OUTPUT_ROOT,
        exist_ok=True
    )

    # --------------------------------------------------------------
    # Global counters
    # --------------------------------------------------------------

    total_graphs = 0
    total_injections = 0
    total_matched = 0
    total_unmatched = 0

    global_records = []

    global_report = {}

    # ==================================================================
    # Vulnerability loop
    # ==================================================================

    for vulnerability in VULNERABILITIES:

        print(
            vulnerability
        )

        print(
            "-" * 70
        )

        graph_dir = os.path.join(
            GRAPH_ROOT,
            vulnerability
        )

        output_dir = os.path.join(
            OUTPUT_ROOT,
            vulnerability
        )

        os.makedirs(
            output_dir,
            exist_ok=True
        )

        vulnerability_report = {

            "graphs": 0,

            "total_injections": 0,

            "matched_injections": 0,

            "unmatched_injections": 0,

            "total_positive_nodes": 0,

            "contracts": {}
        }

        if not os.path.isdir(
            graph_dir
        ):

            print(
                f"WARNING: graph directory does not exist: "
                f"{graph_dir}"
            )

            continue

        # --------------------------------------------------------------
        # Graph files
        # --------------------------------------------------------------

        graph_files = [

            filename

            for filename in os.listdir(
                graph_dir
            )

            if filename.endswith(".pt")
        ]

        graph_files.sort(
            key=lambda filename: (
                contract_number_from_graph(
                    filename
                )
                or 999999
            )
        )

        print(
            f"Contracts: {len(graph_files)}"
        )

        print()

        # ==============================================================
        # Contract loop
        # ==============================================================

        for graph_file in graph_files:

            contract_id = (
                contract_number_from_graph(
                    graph_file
                )
            )

            if contract_id is None:

                print(
                    "WARNING: Cannot determine contract ID:",
                    graph_file
                )

                continue

            graph_path = os.path.join(
                graph_dir,
                graph_file
            )

            # ----------------------------------------------------------
            # Load graph
            # ----------------------------------------------------------

            graph = torch.load(
                graph_path,
                map_location="cpu"
            )

            # ----------------------------------------------------------
            # Verify clean graph structure
            # ----------------------------------------------------------

            required_attributes = [

                "node_type_name",

                "node_start",

                "node_end",

                "parent_index"
            ]

            missing = [

                attribute

                for attribute in required_attributes

                if not hasattr(
                    graph,
                    attribute
                )
            ]

            if missing:

                raise RuntimeError(
                    f"Graph {graph_path} is missing required "
                    f"clean-AST attributes: {missing}"
                )

            # ----------------------------------------------------------
            # Load exact source
            # ----------------------------------------------------------

            source_bytes = load_source(
                vulnerability,
                contract_id
            )

            # ----------------------------------------------------------
            # Load exact BugLog
            # ----------------------------------------------------------

            injections = load_buglog(
                vulnerability,
                contract_id
            )

            # ----------------------------------------------------------
            # Annotate
            # ----------------------------------------------------------

            (
                matched,
                unmatched,
                injection_records
            ) = annotate_graph(
                graph,
                injections,
                source_bytes
            )

            # ----------------------------------------------------------
            # Save annotated graph
            # ----------------------------------------------------------

            output_path = os.path.join(
                output_dir,
                graph_file
            )

            torch.save(
                graph,
                output_path
            )

            # ----------------------------------------------------------
            # Positive node count
            # ----------------------------------------------------------

            positive_nodes = int(
                graph.injection_label.sum().item()
            )

            # ----------------------------------------------------------
            # Save records
            # ----------------------------------------------------------

            for record in injection_records:

                global_records.append({

                    "vulnerability":
                        vulnerability,

                    "contract_id":
                        contract_id,

                    "graph":
                        graph_file,

                    **record
                })

            # ----------------------------------------------------------
            # Update counters
            # ----------------------------------------------------------

            num_injections = len(
                injections
            )

            vulnerability_report[
                "graphs"
            ] += 1

            vulnerability_report[
                "total_injections"
            ] += num_injections

            vulnerability_report[
                "matched_injections"
            ] += matched

            vulnerability_report[
                "unmatched_injections"
            ] += unmatched

            vulnerability_report[
                "total_positive_nodes"
            ] += positive_nodes

            vulnerability_report[
                "contracts"
            ][str(contract_id)] = {

                "graph":
                    graph_file,

                "source":
                    f"buggy_{contract_id}.sol",

                "buglog":
                    f"BugLog_{contract_id}.csv",

                "nodes":
                    int(graph.num_nodes),

                "edges":
                    int(graph.edge_index.shape[1]),

                "injections":
                    num_injections,

                "matched":
                    matched,

                "unmatched":
                    unmatched,

                "positive_nodes":
                    positive_nodes,

                "matching_rate":
                    (
                        matched /
                        num_injections *
                        100
                    )
                    if num_injections
                    else 0.0
            }

            total_graphs += 1

            total_injections += (
                num_injections
            )

            total_matched += matched

            total_unmatched += unmatched

        # ==============================================================
        # Vulnerability summary
        # ==============================================================

        global_report[
            vulnerability
        ] = vulnerability_report

        vuln_total = (
            vulnerability_report[
                "total_injections"
            ]
        )

        vuln_matched = (
            vulnerability_report[
                "matched_injections"
            ]
        )

        vuln_unmatched = (
            vulnerability_report[
                "unmatched_injections"
            ]
        )

        vuln_positive = (
            vulnerability_report[
                "total_positive_nodes"
            ]
        )

        vuln_rate = (

            vuln_matched /
            vuln_total *
            100

        ) if vuln_total else 0.0

        print(
            f"Graphs: {vulnerability_report['graphs']}"
        )

        print(
            f"Injections: {vuln_total}"
        )

        print(
            f"Matched: {vuln_matched}"
        )

        print(
            f"Unmatched: {vuln_unmatched}"
        )

        print(
            f"Matching rate: {vuln_rate:.2f} %"
        )

        print(
            f"Positive nodes: {vuln_positive}"
        )

        print()

    # ==================================================================
    # Global statistics
    # ==================================================================

    global_rate = (

        total_matched /
        total_injections *
        100

    ) if total_injections else 0.0

    # --------------------------------------------------------------
    # Count positive nodes
    # --------------------------------------------------------------

    total_positive_nodes = 0
    total_nodes = 0

    for vulnerability in VULNERABILITIES:

        output_dir = os.path.join(
            OUTPUT_ROOT,
            vulnerability
        )

        if not os.path.isdir(
            output_dir
        ):
            continue

        for filename in os.listdir(
            output_dir
        ):

            if not filename.endswith(".pt"):
                continue

            path = os.path.join(
                output_dir,
                filename
            )

            graph = torch.load(
                path,
                map_location="cpu"
            )

            total_nodes += int(
                graph.num_nodes
            )

            total_positive_nodes += int(
                graph.injection_label.sum().item()
            )

    positive_ratio = (

        total_positive_nodes /
        total_nodes

    ) if total_nodes else 0.0

    # ==================================================================
    # Print summary
    # ==================================================================

    print("=" * 70)

    print(
        "STEP 06 ANNOTATION SUMMARY"
    )

    print("=" * 70)

    print(
        f"Graphs: {total_graphs}"
    )

    print(
        f"Total injections: {total_injections}"
    )

    print(
        f"Matched injections: {total_matched}"
    )

    print(
        f"Unmatched injections: {total_unmatched}"
    )

    print(
        f"Matching rate: {global_rate:.2f} %"
    )

    print(
        f"Total AST nodes: {total_nodes}"
    )

    print(
        f"Positive AST nodes: {total_positive_nodes}"
    )

    print(
        f"Positive-node ratio: {positive_ratio:.6f}"
    )

    # ==================================================================
    # Save injection audit
    # ==================================================================

    audit_path = os.path.join(
        OUTPUT_ROOT,
        "injection_audit.csv"
    )

    write_injection_audit(
        audit_path,
        global_records
    )

    # ==================================================================
    # Save manual examples
    # ==================================================================

    examples_path = os.path.join(
        OUTPUT_ROOT,
        "annotation_examples.txt"
    )

    with open(
        examples_path,
        "w",
        encoding="utf-8"
    ) as f:

        f.write(
            "SecureGAT-Agent Step 06 "
            "Annotation Examples\n"
        )

        f.write(
            "=" * 70
        )

        f.write("\n\n")

        for vulnerability in VULNERABILITIES:

            f.write(
                f"Vulnerability: {vulnerability}\n"
            )

            f.write(
                "-" * 70
            )

            f.write("\n")

            examples = [

                record

                for record in global_records

                if record[
                    "vulnerability"
                ] == vulnerability
            ][:MAX_EXAMPLES_PER_VULNERABILITY]

            for record in examples:

                f.write(
                    f"\nContract: buggy_"
                    f"{record['contract_id']}\n"
                )

                f.write(
                    f"Injection ID: "
                    f"{record['injection_id']}\n"
                )

                f.write(
                    f"BugLog line: "
                    f"{record['loc']}\n"
                )

                f.write(
                    f"Length: "
                    f"{record['length']}\n"
                )

                f.write(
                    f"Source interval: "
                    f"[{record.get('source_start')}, "
                    f"{record.get('source_end')})\n"
                )

                f.write(
                    f"Matched: "
                    f"{record['matched']}\n"
                )

                f.write(
                    f"Selection method: "
                    f"{record.get('selection_method')}\n"
                )

                f.write(
                    f"Matched nodes: "
                    f"{record.get('matched_nodes')}\n"
                )

                f.write(
                    f"Node types: "
                    f"{record.get('node_types')}\n"
                )

                f.write(
                    "\n"
                )

            f.write("\n")

    # ==================================================================
    # Save JSON report
    # ==================================================================

    report = {

        "dataset":
            "SolidiFI-benchmark",

        "step":
            "06_injection_annotation_v2",

        "annotation_version":
            "step06_v2_clean_ast",

        "annotation_strategy":
            ANNOTATION_STRATEGY,

        "execution_device":
            "cpu",

        "graphs":
            total_graphs,

        "total_injections":
            total_injections,

        "matched_injections":
            total_matched,

        "unmatched_injections":
            total_unmatched,

        "matching_rate":
            global_rate,

        "total_nodes":
            total_nodes,

        "positive_nodes":
            total_positive_nodes,

        "positive_node_ratio":
            positive_ratio,

        "vulnerabilities":
            global_report,

        "files": {

            "injection_audit":
                "injection_audit.csv",

            "annotation_examples":
                "annotation_examples.txt"
        }
    }

    report_path = os.path.join(
        OUTPUT_ROOT,
        "annotation_report.json"
    )

    with open(
        report_path,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            report,
            f,
            indent=2
        )

    # ==================================================================
    # Final
    # ==================================================================

    print()

    print(
        f"Report: {report_path}"
    )

    print(
        f"Audit: {audit_path}"
    )

    print(
        f"Examples: {examples_path}"
    )

    print()

    print("=" * 70)

    print(
        "STEP 06 COMPLETE"
    )

    print("=" * 70)


# ======================================================================
# Entry point
# ======================================================================

if __name__ == "__main__":
    main()